### ISSUE TITLE
如何推理预测？

### ISSUE THREAD

**Issue by pythonla** [shawroad/CoSENT_Pytorch#1]
感谢大佬用torch实现，请问怎么推理预测呀？ 难道还要连接全连接层？

**Comment by shawroad** [comment]
> 

不用呀。   跟sentencebert一样的用法。    假设你要做a和b的相关性计算，就是将a和b编码成向量，然后计算cos就行。

**Comment by pythonla** [comment]
这是来自QQ邮箱的假期自动回复邮件。你发给我的信件已经收到。谢谢!

**Comment by pythonla** [comment]
> > 
> 
> 不用呀。 跟sentencebert一样的用法。 假设你要做a和b的相关性计算，就是将a和b编码成向量，然后计算cos就行。

然后自己指定阈值？

**Comment by shawroad** [comment]
看你想干什么了~ .   如果你是做召回的，就按相关分排序。  如果你要判断相关和不相关，就需要指定阈值。

**Comment by pythonla** [comment]
> 看你想干什么了~ . 如果你是做召回的，就按相关分排序。 如果你要判断相关和不相关，就需要指定阈值。

明白了，感谢！
