### ISSUE TITLE
损失一般收敛到最后是多少呢？

### ISSUE THREAD

**Issue by muyuuuu** [shawroad/CoSENT_Pytorch#4]
就是问一下，损失一般收敛到最后是多少呢？我是基于 chinese-roberta-wwm-ext 微调的。实验参数和你的 config 里面保持一致，但仿佛 3.3 左右就不动了....

**Comment by muyuuuu** [comment]
而且 spearman 系数也是稳定在 0.8，就是，后面那几个 epoch 仿佛没有优化。虽然 spearman 很高，但是生成文本向量后，构建向量索引，MRR 指标的得分很低。

这个是距离的原因嘛？训练的时候使用的余弦距离，构建向量索引查询用的是欧氏距离。

**Comment by shawroad** [comment]
训练的时候使用的余弦距离，构建向量索引查询用的是欧氏距离。?????   为啥是这种操作？？   我当时的损失大概是降到0.0x.   建议你训练和检索保持一致。

**Comment by muyuuuu** [comment]
> 练的时候使用的余弦距离，构建向量索引查询用的是欧氏距离。????? 为啥是这种操作？

这个是我的失误，但 cos 训练的话，结果比欧式训练要好。


> 我当时的损失大概是降到0.0x.

我发现忘了乘 lamba，最后降到 0.0X 了，但检索效果依然很差（欧式训练欧式检索更差）。我在冷静分析分析吧

感谢您的回复。

**Comment by muyuuuu** [comment]
实验出结果了，CoSENT 根本没用，simcse 结果很好。
