### ISSUE TITLE
sentence bert的loss函数不应该是u,v,|u-v|拼接吗？您直接就算的cos的MSE

### ISSUE THREAD

**Issue by LYMAXPUP** [shawroad/CoSENT_Pytorch#8]
不是很理解，感觉和苏神那版不太一样

**Comment by shawroad** [comment]
可以去看一下原始的sentencebert论文，有几种方式。 这两种方式论文中都提到了。

**Comment by shawroad** [comment]
学习语义匹配，可以参考这个库https://github.com/shawroad/Semantic-Textual-Similarity-Pytorch
